name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: "Prerelease"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"

      - name: Tag
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: ${{ inputs.prerelease }}
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
  
  build:
    needs: tag
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        os:
          [
            { rid: "win-x64", runs-on: 'windows-latest' },
            { rid: "linux-x64", runs-on: 'ubuntu-latest' },
            { rid: "osx-x64", runs-on: 'macos-latest' },
            # ARM runners aren't generally available yet, and NAOT can't be cross-compiled
          ]
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag.outputs.new_tag }}

      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Install dependencies
        run: dotnet restore -r ${{ matrix.os.rid }}

      - name: Publish
        run: dotnet publish ModTools/ModTools.csproj -c Release --no-restore -o ./${{ matrix.os.rid }} -r ${{ matrix.os.rid }} --no-self-contained

      - name: Compress
        if: ${{ matrix.os.runs-on != 'windows-latest' }}
        run: zip -r ${{ matrix.os.rid }}.zip ./${{ matrix.os.rid }}/*

      - name: Compress
        if: ${{ matrix.os.runs-on == 'windows-latest' }}
        run: Compress-Archive -DestinationPath ${{ matrix.os.rid }}.zip -Path ./${{ matrix.os.rid }}/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.rid }}.zip
          path: ./${{ matrix.os.rid }}.zip
  
  make-release:
    needs:
      - tag
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag.outputs.new_tag }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Make release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: ./artifacts/**/*
          tag_name: ${{ needs.tag.outputs.new_tag }}

